package GUI;

import BUS._MessageDialogHelper;
import BUS._ShareData;

import javax.swing.*;
import java.awt.*;
import java.util.Objects;

public class MainFormGUI extends javax.swing.JFrame {
    private StudentManagePanelGUI mnuStudentManagePanel;
    private ScorceManagePanelGUI mnuScoreManagerPanel;

    /**
     * Creates new form MainForm
     */
    public MainFormGUI() {
        this.initComponents();
        this.processLoginSuccessful();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        plToolBar = new javax.swing.JPanel();
        tBar_Main = new javax.swing.JToolBar();
        tBar_Logout = new javax.swing.JButton();
        tBar_Separator1 = new javax.swing.JToolBar.Separator();
        tBar_StudentManage = new javax.swing.JButton();
        tBar_ScoreManage = new javax.swing.JButton();
        tBar_Separator2 = new javax.swing.JToolBar.Separator();
        tBar_Introdutuon = new javax.swing.JButton();
        plStatus = new javax.swing.JPanel();
        lbUser = new javax.swing.JLabel();
        lbUserType = new javax.swing.JLabel();
        lbStatusUser = new javax.swing.JLabel();
        lbStatusUserTyper = new javax.swing.JLabel();
        tPane_Main = new javax.swing.JTabbedPane();
        mnuBar_Main = new javax.swing.JMenuBar();
        mnuSystem = new javax.swing.JMenu();
        mnuSystem_Logout = new javax.swing.JMenuItem();
        mnuSystem_Separator = new javax.swing.JPopupMenu.Separator();
        mnuSystem_Exit = new javax.swing.JMenuItem();
        mnuManage = new javax.swing.JMenu();
        mnuManage_StudentManage = new javax.swing.JMenuItem();
        mnuManage_Separator = new javax.swing.JPopupMenu.Separator();
        mnuManage_ScoreManage = new javax.swing.JMenuItem();
        mnuHelper = new javax.swing.JMenu();
        mnuHelper_Content = new javax.swing.JMenuItem();
        mnuHelper_Separator = new javax.swing.JPopupMenu.Separator();
        mnuHelper_Introduction = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(String.format("Phần mềm quản lí sinh viên v1.2 - Xin chào %s", _ShareData.getUsername()));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        plToolBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tBar_Logout.setIcon(new javax.swing.ImageIcon("resource\\iconSys\\logout-icon-32.png")); // NOI18N
        tBar_Logout.setText("Đăng xuất");
        tBar_Logout.setFocusable(false);
        tBar_Logout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tBar_Logout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tBar_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBar_LogoutActionPerformed(evt);
            }
        });
        tBar_Main.add(tBar_Logout);
        tBar_Main.add(tBar_Separator1);

        tBar_StudentManage.setIcon(new javax.swing.ImageIcon("resource\\iconSys\\10207-man-student-light-skin-tone-icon-32.png")); // NOI18N
        tBar_StudentManage.setText("Quản lí sinh viên");
        tBar_StudentManage.setFocusable(false);
        tBar_StudentManage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tBar_StudentManage.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tBar_StudentManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBar_StudentManageActionPerformed(evt);
            }
        });
        tBar_Main.add(tBar_StudentManage);

        tBar_ScoreManage.setIcon(new javax.swing.ImageIcon("resource\\iconSys\\gpa-icon-32.png")); // NOI18N
        tBar_ScoreManage.setText("Quản lí điểm thi");
        tBar_ScoreManage.setFocusable(false);
        tBar_ScoreManage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tBar_ScoreManage.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tBar_ScoreManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBar_ScoreManageActionPerformed(evt);
            }
        });
        tBar_Main.add(tBar_ScoreManage);
        tBar_Main.add(tBar_Separator2);

        tBar_Introdutuon.setIcon(new javax.swing.ImageIcon("resource\\iconSys\\Actions-help-about-icon-32.png")); // NOI18N
        tBar_Introdutuon.setText("Giới thiệu");
        tBar_Introdutuon.setFocusable(false);
        tBar_Introdutuon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tBar_Introdutuon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tBar_Introdutuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBar_IntrodutuonActionPerformed(evt);
            }
        });
        tBar_Main.add(tBar_Introdutuon);

        javax.swing.GroupLayout plToolBarLayout = new javax.swing.GroupLayout(plToolBar);
        plToolBar.setLayout(plToolBarLayout);
        plToolBarLayout.setHorizontalGroup(
                plToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 384, Short.MAX_VALUE)
                        .addGroup(plToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tBar_Main, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE))
        );
        plToolBarLayout.setVerticalGroup(
                plToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(plToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tBar_Main, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
        );

        plStatus.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbUser.setText("UserType:");

        lbUserType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbUserType.setText("User:");

        lbStatusUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbStatusUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbStatusUserTyper.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbStatusUserTyper.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout plStatusLayout = new javax.swing.GroupLayout(plStatus);
        plStatus.setLayout(plStatusLayout);
        plStatusLayout.setHorizontalGroup(
                plStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(plStatusLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(plStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbUser)
                                        .addComponent(lbUserType))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(plStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbStatusUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbStatusUserTyper, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                                .addContainerGap())
        );
        plStatusLayout.setVerticalGroup(
                plStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plStatusLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(plStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbUserType)
                                        .addComponent(lbStatusUser))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(plStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbUser)
                                        .addComponent(lbStatusUserTyper))
                                .addContainerGap(10, Short.MAX_VALUE))
        );

        mnuSystem.setText("Hệ thống");

        mnuSystem_Logout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuSystem_Logout.setIcon(new javax.swing.ImageIcon("resource\\iconSys\\logout-icon-16.png")); // NOI18N
        mnuSystem_Logout.setText("Đăng xuất");
        mnuSystem_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSystem_LogoutActionPerformed(evt);
            }
        });
        mnuSystem.add(mnuSystem_Logout);
        mnuSystem.add(mnuSystem_Separator);

        mnuSystem_Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuSystem_Exit.setIcon(new javax.swing.ImageIcon("resource\\iconSys\\Button-Close-icon-16.png")); // NOI18N
        mnuSystem_Exit.setText("Thoát");
        mnuSystem_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSystem_ExitActionPerformed(evt);
            }
        });
        mnuSystem.add(mnuSystem_Exit);

        mnuBar_Main.add(mnuSystem);

        mnuManage.setText("Quản lí");

        mnuManage_StudentManage.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuManage_StudentManage.setIcon(new javax.swing.ImageIcon("resource\\iconSys\\10207-man-student-light-skin-tone-icon-16.png")); // NOI18N
        mnuManage_StudentManage.setText("Quản lí sinh viên");
        mnuManage_StudentManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManage_StudentManageActionPerformed(evt);
            }
        });
        mnuManage.add(mnuManage_StudentManage);
        mnuManage.add(mnuManage_Separator);

        mnuManage_ScoreManage.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuManage_ScoreManage.setIcon(new javax.swing.ImageIcon("resource\\iconSys\\gpa-icon.png")); // NOI18N
        mnuManage_ScoreManage.setText("Quản lí điểm thi");
        mnuManage_ScoreManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManage_ScoreManageActionPerformed(evt);
            }
        });
        mnuManage.add(mnuManage_ScoreManage);

        mnuBar_Main.add(mnuManage);

        mnuHelper.setText("Trợ giúp");

        mnuHelper_Content.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuHelper_Content.setIcon(new javax.swing.ImageIcon("resource\\iconSys\\Actions-help-about-icon-16.png")); // NOI18N
        mnuHelper_Content.setText("Nội dung");
        mnuHelper_Content.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHelper_ContentActionPerformed(evt);
            }
        });
        mnuHelper.add(mnuHelper_Content);
        mnuHelper.add(mnuHelper_Separator);

        mnuHelper_Introduction.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuHelper_Introduction.setIcon(new javax.swing.ImageIcon("resource\\iconSys\\Help-icon-16.png")); // NOI18N
        mnuHelper_Introduction.setText("Giới thiệu");
        mnuHelper_Introduction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHelper_IntroductionActionPerformed(evt);
            }
        });
        mnuHelper.add(mnuHelper_Introduction);

        mnuBar_Main.add(mnuHelper);

        setJMenuBar(mnuBar_Main);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tPane_Main, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(plToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(plStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(plStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(plToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tPane_Main, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    // xử lí các button
    private void mnuManage_StudentManageActionPerformed(java.awt.event.ActionEvent evt) {
        if(mnuStudentManagePanel == null) {
            mnuStudentManagePanel = new StudentManagePanelGUI();
            String path = "resource/iconSys/10207-man-student-light-skin-tone-icon-16.png";
            tPane_Main.addTab("Quản lí sinh viên", new ImageIcon(path), mnuStudentManagePanel, "Quản lí sinh viên");
        } else {
            tPane_Main.setSelectedComponent(mnuStudentManagePanel);
        }
    }

    private void mnuManage_ScoreManageActionPerformed(java.awt.event.ActionEvent evt) {
        if(mnuScoreManagerPanel == null) {
            mnuScoreManagerPanel = new ScorceManagePanelGUI();
            String path = "resource/iconSys/gpa-icon.png";
            tPane_Main.addTab("Quản lí sinh viên", new ImageIcon(path), mnuScoreManagerPanel, "Quản lí sinh viên");
        } else {
            tPane_Main.setSelectedComponent(mnuScoreManagerPanel);
        }
    }

    private void mnuHelper_IntroductionActionPerformed(java.awt.event.ActionEvent evt) {
        AboutUSDIalogGUI aboutDialog = new AboutUSDIalogGUI(this, true);
        aboutDialog.setVisible(true);
    }

    private void mnuSystem_LogoutActionPerformed(java.awt.event.ActionEvent evt) {
        if(_MessageDialogHelper.showConfirmDialog(this, "Bạn có muốn đăng xuất hay không",
                "Đăng xuất") == JOptionPane.YES_OPTION) {
            this.dispose(); // đóng form hiện tại lại
            new LoginDialogGUI(new Frame(), true).setVisible(true);
        }
    }

    private void mnuSystem_ExitActionPerformed(java.awt.event.ActionEvent evt) {
        if(_MessageDialogHelper.showConfirmDialog(this, "Bạn có muốn thoát khỏi chương trình hay không",
                "Thoát chương trình") == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    private void mnuHelper_ContentActionPerformed(java.awt.event.ActionEvent evt) {
        _MessageDialogHelper.showErrorDialog(this, "Tính năng đang trong quá trình hoàn thiện !",
                "Đang cập nhật");
    }

    // xử lí tabBar hệ thống
    private void tBar_LogoutActionPerformed(java.awt.event.ActionEvent evt) {
        if(_MessageDialogHelper.showConfirmDialog(this, "Bạn có muốn đăng xuất hay không",
                "Đăng xuất") == JOptionPane.YES_OPTION) {
            this.dispose(); // đóng form hiện tại lại
            new LoginDialogGUI(new Frame(), true).setVisible(true);
        }
    }

    private void tBar_StudentManageActionPerformed(java.awt.event.ActionEvent evt) {
        if(mnuStudentManagePanel == null) {
            mnuStudentManagePanel = new StudentManagePanelGUI();
            String path = "resource/iconSys/10207-man-student-light-skin-tone-icon-16.png";
            tPane_Main.addTab("Quản lí sinh viên", new ImageIcon(path),
                    mnuStudentManagePanel, "Quản lí sinh viên");
        }
        tPane_Main.setSelectedComponent(mnuStudentManagePanel);
    }

    private void tBar_ScoreManageActionPerformed(java.awt.event.ActionEvent evt) {
        if(mnuScoreManagerPanel == null) {
            mnuScoreManagerPanel = new ScorceManagePanelGUI();
            String path = "resource/iconSys/gpa-icon.png";
            tPane_Main.addTab("Quản lí sinh viên", new ImageIcon(path),
                    mnuScoreManagerPanel, "Quản lí sinh viên");
        }
        tPane_Main.setSelectedComponent(mnuScoreManagerPanel);
    }

    private void tBar_IntrodutuonActionPerformed(java.awt.event.ActionEvent evt) {
        AboutUSDIalogGUI aboutDialog = new AboutUSDIalogGUI(this, true);
        aboutDialog.setVisible(true);
    }

    private void processLoginSuccessful() {
        lbStatusUser.setText(_ShareData.getUsername());
        lbStatusUserTyper.setText(_ShareData.getTypeUser());
        tPane_Main.removeAll();
        if(_ShareData.getTypeUser().equals("Admin")) {
            tBar_StudentManage.setEnabled(true);
            tBar_ScoreManage.setEnabled(true);
            mnuManage_ScoreManage.setEnabled(true);
            mnuManage_StudentManage.setEnabled(true);
        } else if(_ShareData.getTypeUser().equals("Giảng Viên")) {
            tBar_StudentManage.setEnabled(false);
            tBar_ScoreManage.setEnabled(true);
            mnuManage_ScoreManage.setEnabled(true);
            mnuManage_StudentManage.setEnabled(false);
        }
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel lbStatusUser;
    private javax.swing.JLabel lbStatusUserTyper;
    private javax.swing.JLabel lbUser;
    private javax.swing.JLabel lbUserType;
    private javax.swing.JMenuBar mnuBar_Main;
    private javax.swing.JMenu mnuHelper;
    private javax.swing.JMenuItem mnuHelper_Content;
    private javax.swing.JMenuItem mnuHelper_Introduction;
    private javax.swing.JPopupMenu.Separator mnuHelper_Separator;
    private javax.swing.JMenu mnuManage;
    private javax.swing.JMenuItem mnuManage_ScoreManage;
    private javax.swing.JPopupMenu.Separator mnuManage_Separator;
    private javax.swing.JMenuItem mnuManage_StudentManage;
    private javax.swing.JMenu mnuSystem;
    private javax.swing.JMenuItem mnuSystem_Exit;
    private javax.swing.JMenuItem mnuSystem_Logout;
    private javax.swing.JPopupMenu.Separator mnuSystem_Separator;
    private javax.swing.JPanel plStatus;
    private javax.swing.JPanel plToolBar;
    private javax.swing.JButton tBar_Introdutuon;
    private javax.swing.JButton tBar_Logout;
    private javax.swing.JToolBar tBar_Main;
    private javax.swing.JButton tBar_ScoreManage;
    private javax.swing.JToolBar.Separator tBar_Separator1;
    private javax.swing.JToolBar.Separator tBar_Separator2;
    private javax.swing.JButton tBar_StudentManage;
    private javax.swing.JTabbedPane tPane_Main;
    // End of variables declaration
}


