package GUI;

import BUS.StudentBUS;
import BUS._DataValidator;
import BUS._MessageDialogHelper;
import BUS._SaveImage;
import DAO.StudentDAO;
import DTO.StudentDTO;

import javax.swing.*;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.util.ArrayList;
import java.util.Objects;

public class StudentManagePanelGUI extends javax.swing.JPanel {
    private MainFormGUI parrentForm;
    private DefaultTableModel model_table;
    private byte[] personalImage;

    /**
     * Creates new form StudentManagePanel
     */
    public StudentManagePanelGUI() {
        initDataTable();
        initComponents();
    }

    private void initDataTable() {
        String[] columnNames = new String[] {"idStudent", "name", "email", "phoneNumber", "sex", "address"};
        model_table = new DefaultTableModel();
        model_table.setColumnIdentifiers(columnNames);

        try {
            ArrayList<StudentDTO> listStudent = new StudentBUS().getListStudent();
            this.model_table.setRowCount(0);
            listStudent.forEach(item -> {
                model_table.addRow(new Object[] {
                        item.getIdStudent().trim(),
                        item.getName().trim(),
                        item.getEmail().trim(),
                        item.getPhoneNumber().trim(),
                        item.getSex() == 1 ? "Male" : "Female",
                        item.getAddress().trim()
                });
            });
        } catch (Exception ex) {
            ex.printStackTrace();
            _MessageDialogHelper.showErrorDialog(parrentForm, ex.getMessage(), "Error !");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        grBtn_Sex = new javax.swing.ButtonGroup();
        lbTitle = new javax.swing.JLabel();
        srt1 = new javax.swing.JSeparator();
        lbIdSinhVien = new javax.swing.JLabel();
        lbHoTen = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbPhoneNumber = new javax.swing.JLabel();
        lbSex = new javax.swing.JLabel();
        lbAddress = new javax.swing.JLabel();
        txtIdSinhVien = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        pAvatar = new javax.swing.JPanel();
        lbAvatar = new javax.swing.JLabel();
        btnSetAvatar = new javax.swing.JButton();
        sPanelAddress = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        btnRefresh = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        tblPanel = new javax.swing.JPanel();
        tblScrollPane = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        rbMale = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();

        lbTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbTitle.setText("Quản lí sinh viên");

        lbIdSinhVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbIdSinhVien.setText("Mã sinh viên");

        lbHoTen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbHoTen.setText("Họ tên");

        lbEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbEmail.setText("Email");

        lbPhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbPhoneNumber.setText("Số điện thoại");

        lbSex.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbSex.setText("Giới tính");

        lbAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbAddress.setText("Địa chỉ ");

        txtIdSinhVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtHoTen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtPhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        pAvatar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAvatar.setIcon(new javax.swing.ImageIcon("resource\\iconSys\\10207-man-student-light-skin-tone-icon-64.png")); // NOI18N

        btnSetAvatar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSetAvatar.setIcon(new javax.swing.ImageIcon("resource\\iconSys\\open-file-icon-16.png")); // NOI18N
        btnSetAvatar.setText("Mở hình");
        btnSetAvatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetAvatarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pAvatarLayout = new javax.swing.GroupLayout(pAvatar);
        pAvatar.setLayout(pAvatarLayout);
        pAvatarLayout.setHorizontalGroup(
                pAvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pAvatarLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbAvatar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAvatarLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(btnSetAvatar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(43, 43, 43))
        );
        pAvatarLayout.setVerticalGroup(
                pAvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pAvatarLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                .addComponent(btnSetAvatar)
                                .addContainerGap())
        );

        txtAddress.setColumns(20);
        txtAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAddress.setRows(5);
        sPanelAddress.setViewportView(txtAddress);

        btnRefresh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRefresh.setIcon(new javax.swing.ImageIcon("resource\\iconSys\\new-icon-16.png")); // NOI18N
        btnRefresh.setText("Tạo mới");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon("resource\\iconSys\\Actions-document-edit-icon-16.png")); // NOI18N
        btnUpdate.setText("Cập nhật");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon("resource\\iconSys\\Save-icon.png")); // NOI18N
        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon("resource\\iconSys\\Actions-edit-delete-icon-16.png")); // NOI18N
        btnDelete.setText("Xoá");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });


        tblStudents.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblStudents.setModel(model_table);
        tblStudents.addMouseListener(new MouseListener()  {
            @Override
            public void mouseClicked(MouseEvent e) {

            }

            public void mousePressed(MouseEvent e) {
                tblStudentsMousePressed(e);
            }

            @Override
            public void mouseReleased(MouseEvent e) {

            }

            @Override
            public void mouseEntered(MouseEvent e) {

            }

            @Override
            public void mouseExited(MouseEvent e) {

            }
        });
        tblScrollPane.setViewportView(tblStudents);

        javax.swing.GroupLayout tblPanelLayout = new javax.swing.GroupLayout(tblPanel);
        tblPanel.setLayout(tblPanelLayout);
        tblPanelLayout.setHorizontalGroup(
                tblPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tblScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
        );
        tblPanelLayout.setVerticalGroup(
                tblPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tblPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(tblScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        grBtn_Sex.add(rbMale);
        rbMale.setText("Nam");

        grBtn_Sex.add(rbFemale);
        rbFemale.setText("Nữ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tblPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(srt1)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(lbAddress)
                                                                                        .addComponent(lbSex))
                                                                                .addGap(37, 37, 37)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(sPanelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(rbMale)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(rbFemale)
                                                                                                .addGap(0, 0, Short.MAX_VALUE))))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                        .addComponent(lbHoTen)
                                                                                                        .addComponent(lbEmail)
                                                                                                        .addComponent(lbIdSinhVien))
                                                                                                .addGap(11, 11, 11))
                                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                                .addComponent(lbPhoneNumber)
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(txtIdSinhVien, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                        .addComponent(txtHoTen)
                                                                                        .addComponent(txtPhoneNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                        .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING))))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(pAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(lbTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addComponent(btnRefresh)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnDelete)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lbTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(srt1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lbIdSinhVien)
                                                        .addComponent(txtIdSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lbHoTen)
                                                        .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lbEmail, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addGap(16, 16, 16)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lbPhoneNumber))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lbSex)
                                                        .addComponent(rbMale)
                                                        .addComponent(rbFemale))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lbAddress)
                                                        .addComponent(sPanelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(pAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnRefresh)
                                        .addComponent(btnDelete)
                                        .addComponent(btnUpdate)
                                        .addComponent(btnSave))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addComponent(tblPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>

    private void btnSetAvatarActionPerformed(java.awt.event.ActionEvent evt) {
        // config thao tác chọn file
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileFilter() {
            @Override
            public boolean accept(File f) {
                if(f.isDirectory())  {
                    return true; // nếu mở trúng folder thì trả về true để mở tiếp
                } else {
                    // trong csdl không có chứa trường để lưu lại phần mở rộng của hình ảnh
                    // và chỉ có một trường Img dể lưu nội dung của hình => ngầm định chỉ làm việc với duy nhất .jpg
                    return f.getName().toLowerCase().endsWith(".jpg");
                }
            }

            @Override
            public String getDescription() {
                return "Image File (*.png)"; // set nội dung file chỉ mở được file .png
            }
        });

        // nếu đã chọn file xong
        if(fileChooser.showOpenDialog(parrentForm) == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile(); // lấy đường dẫn file đã chọn
            try {
                ImageIcon icon = new ImageIcon(file.getPath()); // khởi tạo imageIcon
                Image img = _SaveImage.resize(icon.getImage(), 140, 140); // resize kích thước imageIcon
                ImageIcon resizedIcon = new ImageIcon(img); // sau khi đã resize lại kích thước của image thì khởi tạo imageIcon 1 lần nữ
                lbAvatar.setIcon(resizedIcon); // set lại hình ảnh và do hàm setIcon chỉ nhận vào ImageIcon nên ta mới chuyển từ Image => ImageIcon như bước trên
                personalImage = _SaveImage.toByteArray(img, "jpg"); // chuyển image thành dạng byte và lưu nó lại vào biến personImage
            } catch (Exception ex) {
                ex.printStackTrace();
                _MessageDialogHelper.showErrorDialog(parrentForm, ex.getMessage(), "Error");
            }
        }
    }

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {
        refreshData();
        this.txtIdSinhVien.setText("");
        this.txtHoTen.setText("");
        this.txtEmail.setText("");
        this.txtAddress.setText("");
        this.txtPhoneNumber.setText("");
        this.grBtn_Sex.clearSelection();
        this.personalImage = null;
        this.lbAvatar.setIcon(new javax.swing.ImageIcon("resource\\iconSys\\10207-man-student-light-skin-tone-icon-64.png")); // NOI18N
    }

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {
        StringBuilder sb = new StringBuilder();
        try {
            _DataValidator.validateEmpty(txtIdSinhVien, sb, "Mã sinh viên không được để trống !");
            _DataValidator.validateEmpty(txtHoTen, sb, "Họ tên sinh viên không được để trống !");
            _DataValidator.validateEmpty(txtPhoneNumber, sb, "Số điện thoại không được để trống !");
            _DataValidator.validateEmpty(txtAddress, sb, "Địa chỉ nhà không được để trống !");
            _DataValidator.validateEmpty(txtEmail, sb, "Email không được để trống !");
            _DataValidator.validateEmpty(grBtn_Sex, sb, "Giới tính phải được lựa chọn !");

            if(sb.length() > 0) {
                _MessageDialogHelper.showErrorDialog(parrentForm, String.valueOf(sb), "Error Input Value");
            } else {
                if(_MessageDialogHelper.showConfirmDialog(parrentForm,
                        "Bạn có muốn cập nhật dữ liệu cho đối tượng không",
                        "Cập nhật dữ liệu") == JOptionPane.YES_OPTION) {

                    StudentDTO studentDTO = new StudentDTO();
                    studentDTO.setIdStudent(txtIdSinhVien.getText().trim());
                    studentDTO.setName(txtHoTen.getText().trim());
                    studentDTO.setAddress(txtAddress.getText().trim());
                    studentDTO.setPhoneNumber(txtPhoneNumber.getText().trim());
                    studentDTO.setEmail(txtEmail.getText().trim());
                    studentDTO.setSex(rbMale.isSelected() ? 1 : 0);
                    studentDTO.setAvatar(personalImage);

                    StudentDAO studentDAO = new StudentDAO();
                    if(studentDAO.update(studentDTO)) {
                        refreshData(); // cập nhật lại dữ liệu lên GUI
                        _MessageDialogHelper.showMessageDialog(parrentForm, "Cập nhật đối tượng thành công !", "Success Query Data");
                    } else {
                        _MessageDialogHelper.showErrorDialog(parrentForm, "Cập nhật đối tượng thất bại !", "Failure Query Data");
                    }
                }
            }

        } catch (Exception ex) {
            ex.printStackTrace();
            _MessageDialogHelper.showErrorDialog(parrentForm, ex.getMessage(), "Error Query");
        }
    }

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {
        StringBuilder sb = new StringBuilder();
        try {
            _DataValidator.validateEmpty(txtIdSinhVien, sb, "Mã sinh viên không được để trống !");
            _DataValidator.validateEmpty(txtHoTen, sb, "Họ tên sinh viên không được để trống !");
            _DataValidator.validateEmpty(txtPhoneNumber, sb, "Số điện thoại không được để trống !");
            _DataValidator.validateEmpty(txtAddress, sb, "Địa chỉ nhà không được để trống !");
            _DataValidator.validateEmpty(txtEmail, sb, "Email không được để trống !");
            _DataValidator.validateEmpty(grBtn_Sex, sb, "Giới tính phải được lựa chọn !");

            if(sb.length() > 0) {
                _MessageDialogHelper.showErrorDialog(parrentForm, String.valueOf(sb), "Error Input Value");
            } else {
                StudentDTO studentDTO = new StudentDTO();
                studentDTO.setIdStudent(txtIdSinhVien.getText().trim());
                studentDTO.setName(txtHoTen.getText().trim());
                studentDTO.setAddress(txtAddress.getText().trim());
                studentDTO.setPhoneNumber(txtPhoneNumber.getText().trim());
                studentDTO.setEmail(txtEmail.getText().trim());
                studentDTO.setSex(rbMale.isSelected() ? 1 : 0);
                studentDTO.setAvatar(personalImage);

                StudentDAO studentDAO = new StudentDAO();
                if(studentDAO.insert(studentDTO)) {
                    refreshData(); // cập nhật lại dữ liệu lên GUI
                    _MessageDialogHelper.showMessageDialog(parrentForm, "Tạo mới đối tượng thành công !", "Success Query Data");
                } else {
                    _MessageDialogHelper.showErrorDialog(parrentForm, "Tạo mới đối tượng thất bại !", "Failure Query Data");
                }
            }

        } catch (Exception ex) {
            ex.printStackTrace();
            _MessageDialogHelper.showErrorDialog(parrentForm, ex.getMessage(), "Error Query");
        }
    }

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {
        StringBuilder sb = new StringBuilder();
        try {
            _DataValidator.validateEmpty(txtIdSinhVien, sb, "Mã sinh viên không được để trống !");
            if(sb.length() > 0) {
                _MessageDialogHelper.showErrorDialog(parrentForm, String.valueOf(sb), "Error Input Value");
            } else {
                if(_MessageDialogHelper.showConfirmDialog(parrentForm,
                        "Bạn có muốn xoá đối tượng ra khỏi cơ sở dữ liệu không ?",
                        "Xoá dữ liệu") == JOptionPane.YES_OPTION) {

                    StudentDAO studentDAO = new StudentDAO();
                    if(studentDAO.delete(txtIdSinhVien.getText().trim())) {
                        refreshData(); // cập nhật lại dữ liệu lên GUI
                        btnRefreshActionPerformed(evt); // gọi lại event của hàm để clear data khỏi các field
                        _MessageDialogHelper.showMessageDialog(parrentForm, "Xoá đối tượng dữ liệu thành công !", "Success Query Data");
                    } else {
                        _MessageDialogHelper.showErrorDialog(parrentForm, "Xoá đối tượng thất bại !", "Failure Query Data");
                    }
                }
            }

        } catch (Exception ex) {
            ex.printStackTrace();
            _MessageDialogHelper.showErrorDialog(parrentForm, ex.getMessage(), "Error Query");
        }
    }

    private void tblStudentsMousePressed(MouseEvent e) {
        int selectedRow = tblStudents.getSelectedRow();
        printDataIntoField(selectedRow);
    }

    public void printDataIntoField(int selectedRow) {
        try {
            // lấy dữ liệu từ dòng số n cột thứ m trong table
            String id = (String) tblStudents.getValueAt(selectedRow, 0);
            StudentDTO student = new StudentBUS().getStudentById(id.trim());
            if(student != null) {
                txtIdSinhVien.setText(student.getIdStudent().trim());
                txtHoTen.setText(student.getName().trim());
                txtEmail.setText(student.getEmail().trim());
                txtAddress.setText(student.getAddress().trim());
                txtPhoneNumber.setText(student.getPhoneNumber().trim());

                if(student.getAvatar() != null) {
                    Image img = _SaveImage.createImageFromByteArray(student.getAvatar());
                    lbAvatar.setIcon(new ImageIcon(img));
                } else {
                    this.lbAvatar.setIcon(new javax.swing.ImageIcon("resource\\iconSys\\10207-man-student-light-skin-tone-icon-64.png")); // NOI18N
                }

                if(student.getSex() == 1) {
                    rbMale.setSelected(true);
                } else {
                    rbFemale.setSelected(true);
                }

            } else {
                _MessageDialogHelper.showErrorDialog(parrentForm, "Không tìm thấy sinh viên", "Lỗi tìm kiếm");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    public void refreshData() {
        try {
            ArrayList<StudentDTO> listStudent = new StudentBUS().getListStudent();
            this.model_table.setRowCount(0);
            listStudent.forEach(item -> {
                model_table.addRow(new Object[] {
                        item.getIdStudent().trim(),
                        item.getName().trim(),
                        item.getEmail().trim(),
                        item.getPhoneNumber().trim(),
                        item.getSex() == 1 ? "Male" : "Female",
                        item.getAddress().trim()
                });
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSetAvatar;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup grBtn_Sex;
    private javax.swing.JLabel lbAddress;
    private javax.swing.JLabel lbAvatar;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbHoTen;
    private javax.swing.JLabel lbIdSinhVien;
    private javax.swing.JLabel lbPhoneNumber;
    private javax.swing.JLabel lbSex;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JPanel pAvatar;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbMale;
    private javax.swing.JScrollPane sPanelAddress;
    private javax.swing.JSeparator srt1;
    private javax.swing.JPanel tblPanel;
    private javax.swing.JScrollPane tblScrollPane;
    private javax.swing.JTable tblStudents;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtIdSinhVien;
    private javax.swing.JTextField txtPhoneNumber;
    // End of variables declaration
}
