/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.form_asg_qlysinhvien;

/**
 *
 * @author edgar
 */
public class MainFormGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainFormGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plToolBar = new javax.swing.JPanel();
        tBar_Main = new javax.swing.JToolBar();
        tBar_Logout = new javax.swing.JButton();
        tBar_Separator1 = new javax.swing.JToolBar.Separator();
        tBar_StudentManage = new javax.swing.JButton();
        tBar_ScoreManage = new javax.swing.JButton();
        tBar_Separator2 = new javax.swing.JToolBar.Separator();
        tBar_Introdutuon = new javax.swing.JButton();
        plStatus = new javax.swing.JPanel();
        lbUser = new javax.swing.JLabel();
        lbUserType = new javax.swing.JLabel();
        lbStatusUser = new javax.swing.JLabel();
        lbStatusUserTyper = new javax.swing.JLabel();
        tPane_Main = new javax.swing.JTabbedPane();
        mnuBar_Main = new javax.swing.JMenuBar();
        mnuSystem = new javax.swing.JMenu();
        mnuSystem_Logout = new javax.swing.JMenuItem();
        mnuSystem_Separator = new javax.swing.JPopupMenu.Separator();
        mnuSystem_Exit = new javax.swing.JMenuItem();
        mnuManage = new javax.swing.JMenu();
        mnuManage_StudentManage = new javax.swing.JMenuItem();
        mnuManage_Separator = new javax.swing.JPopupMenu.Separator();
        mnuManage_ScoreManage = new javax.swing.JMenuItem();
        mnuHelper = new javax.swing.JMenu();
        mnuHelper_Content = new javax.swing.JMenuItem();
        mnuHelper_Separator = new javax.swing.JPopupMenu.Separator();
        mnuHelper_Introduction = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phần mềm quản lí sinh viên v1.2");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        plToolBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tBar_Logout.setText("Đăng xuất");
        tBar_Logout.setFocusable(false);
        tBar_Logout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tBar_Logout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tBar_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBar_LogoutActionPerformed(evt);
            }
        });
        tBar_Main.add(tBar_Logout);
        tBar_Main.add(tBar_Separator1);

        tBar_StudentManage.setText("Quản lí sinh viên");
        tBar_StudentManage.setFocusable(false);
        tBar_StudentManage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tBar_StudentManage.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tBar_StudentManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBar_StudentManageActionPerformed(evt);
            }
        });
        tBar_Main.add(tBar_StudentManage);

        tBar_ScoreManage.setText("Quản lí điểm thi");
        tBar_ScoreManage.setFocusable(false);
        tBar_ScoreManage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tBar_ScoreManage.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tBar_ScoreManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBar_ScoreManageActionPerformed(evt);
            }
        });
        tBar_Main.add(tBar_ScoreManage);
        tBar_Main.add(tBar_Separator2);

        tBar_Introdutuon.setText("Giới thiệu");
        tBar_Introdutuon.setFocusable(false);
        tBar_Introdutuon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tBar_Introdutuon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tBar_Introdutuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBar_IntrodutuonActionPerformed(evt);
            }
        });
        tBar_Main.add(tBar_Introdutuon);

        javax.swing.GroupLayout plToolBarLayout = new javax.swing.GroupLayout(plToolBar);
        plToolBar.setLayout(plToolBarLayout);
        plToolBarLayout.setHorizontalGroup(
            plToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
            .addGroup(plToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tBar_Main, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE))
        );
        plToolBarLayout.setVerticalGroup(
            plToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(plToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tBar_Main, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
        );

        plStatus.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbUser.setText("UserType:");

        lbUserType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbUserType.setText("User:");

        lbStatusUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbStatusUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbStatusUserTyper.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbStatusUserTyper.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout plStatusLayout = new javax.swing.GroupLayout(plStatus);
        plStatus.setLayout(plStatusLayout);
        plStatusLayout.setHorizontalGroup(
            plStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbUser)
                    .addComponent(lbUserType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(plStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbStatusUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbStatusUserTyper, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                .addContainerGap())
        );
        plStatusLayout.setVerticalGroup(
            plStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plStatusLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(plStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUserType)
                    .addComponent(lbStatusUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUser)
                    .addComponent(lbStatusUserTyper))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        mnuSystem.setText("Hệ thống");

        mnuSystem_Logout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuSystem_Logout.setText("Đăng xuất");
        mnuSystem_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSystem_LogoutActionPerformed(evt);
            }
        });
        mnuSystem.add(mnuSystem_Logout);
        mnuSystem.add(mnuSystem_Separator);

        mnuSystem_Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuSystem_Exit.setText("Thoát");
        mnuSystem_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSystem_ExitActionPerformed(evt);
            }
        });
        mnuSystem.add(mnuSystem_Exit);

        mnuBar_Main.add(mnuSystem);

        mnuManage.setText("Quản lí");
        mnuManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManageActionPerformed(evt);
            }
        });

        mnuManage_StudentManage.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuManage_StudentManage.setText("Quản lí sinh viên");
        mnuManage_StudentManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManage_StudentManageActionPerformed(evt);
            }
        });
        mnuManage.add(mnuManage_StudentManage);
        mnuManage.add(mnuManage_Separator);

        mnuManage_ScoreManage.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuManage_ScoreManage.setText("Quản lí điểm thi");
        mnuManage_ScoreManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManage_ScoreManageActionPerformed(evt);
            }
        });
        mnuManage.add(mnuManage_ScoreManage);

        mnuBar_Main.add(mnuManage);

        mnuHelper.setText("Trợ giúp");

        mnuHelper_Content.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuHelper_Content.setText("Nội dung");
        mnuHelper_Content.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHelper_ContentActionPerformed(evt);
            }
        });
        mnuHelper.add(mnuHelper_Content);
        mnuHelper.add(mnuHelper_Separator);

        mnuHelper_Introduction.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuHelper_Introduction.setText("Giới thiệu");
        mnuHelper_Introduction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHelper_IntroductionActionPerformed(evt);
            }
        });
        mnuHelper.add(mnuHelper_Introduction);

        mnuBar_Main.add(mnuHelper);

        setJMenuBar(mnuBar_Main);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tPane_Main, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(plToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(plStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(plToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tPane_Main, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuManage_StudentManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManage_StudentManageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuManage_StudentManageActionPerformed

    private void tBar_StudentManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBar_StudentManageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBar_StudentManageActionPerformed

    private void tBar_ScoreManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBar_ScoreManageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBar_ScoreManageActionPerformed

    private void tBar_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBar_LogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBar_LogoutActionPerformed

    private void tBar_IntrodutuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBar_IntrodutuonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBar_IntrodutuonActionPerformed

    private void mnuSystem_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSystem_LogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuSystem_LogoutActionPerformed

    private void mnuSystem_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSystem_ExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuSystem_ExitActionPerformed

    private void mnuManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuManageActionPerformed

    private void mnuManage_ScoreManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManage_ScoreManageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuManage_ScoreManageActionPerformed

    private void mnuHelper_IntroductionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHelper_IntroductionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuHelper_IntroductionActionPerformed

    private void mnuHelper_ContentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHelper_ContentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuHelper_ContentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFormGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFormGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFormGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFormGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFormGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbStatusUser;
    private javax.swing.JLabel lbStatusUserTyper;
    private javax.swing.JLabel lbUser;
    private javax.swing.JLabel lbUserType;
    private javax.swing.JMenuBar mnuBar_Main;
    private javax.swing.JMenu mnuHelper;
    private javax.swing.JMenuItem mnuHelper_Content;
    private javax.swing.JMenuItem mnuHelper_Introduction;
    private javax.swing.JPopupMenu.Separator mnuHelper_Separator;
    private javax.swing.JMenu mnuManage;
    private javax.swing.JMenuItem mnuManage_ScoreManage;
    private javax.swing.JPopupMenu.Separator mnuManage_Separator;
    private javax.swing.JMenuItem mnuManage_StudentManage;
    private javax.swing.JMenu mnuSystem;
    private javax.swing.JMenuItem mnuSystem_Exit;
    private javax.swing.JMenuItem mnuSystem_Logout;
    private javax.swing.JPopupMenu.Separator mnuSystem_Separator;
    private javax.swing.JPanel plStatus;
    private javax.swing.JPanel plToolBar;
    private javax.swing.JButton tBar_Introdutuon;
    private javax.swing.JButton tBar_Logout;
    private javax.swing.JToolBar tBar_Main;
    private javax.swing.JButton tBar_ScoreManage;
    private javax.swing.JToolBar.Separator tBar_Separator1;
    private javax.swing.JToolBar.Separator tBar_Separator2;
    private javax.swing.JButton tBar_StudentManage;
    private javax.swing.JTabbedPane tPane_Main;
    // End of variables declaration//GEN-END:variables
}
